version: '3'
services:
  satis:
    container_name: satis
    image: composer/satis
    volumes:
      - ./data/satis/build:/build
      - ./config.json:/build/config.json
      - ./data/satis/composer:/composer
    command:
      - --ansi
      - -vvv
      - build
      - --skip-errors
      - /build/config.json
      - /build/output
  satis_web:
    container_name: satis_web
    image: nginx
    restart: always
    volumes:
      - ./data/satis/build/output:/usr/share/nginx/html
  verdaccio:
    build: verdaccio
    container_name: "verdaccio"
    environment:
      - VERDACCIO_PORT=4873
      - VERDACCIO_USER_UID=0
      - VERDACCIO_USER_NAME="root"
    volumes:
      - ./data/verdaccio/storage:/verdaccio/storage
      - ./data/verdaccio/config:/verdaccio/conf
      - ./data/verdaccio/plugins:/verdaccio/plugins
      - ./verdaccio/config.yaml:/verdaccio/conf/config.yaml
